// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RazorPagesWorkout.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Workout.Model.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Equipment = "",
                            MuscleGroup = "Quads",
                            Name = "Legs",
                            Reps = 15,
                            Sets = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Equipment = "",
                            MuscleGroup = "Hamstrings",
                            Name = "Legs",
                            Reps = 15,
                            Sets = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Equipment = "",
                            MuscleGroup = "Abs",
                            Name = "Abs",
                            Reps = 100,
                            Sets = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Equipment = "",
                            MuscleGroup = "Biceps",
                            Name = "Arms",
                            Reps = 10,
                            Sets = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Duration = 120,
                            Equipment = "",
                            MuscleGroup = "All",
                            Name = "Speed Walking",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Workout.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "morrilk@mail.nmc.edu",
                            Name = "Kyle Morrill"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lbalbach@nmc.edu",
                            Name = "Lisa Balbach"
                        });
                });

            modelBuilder.Entity("Workout.Model.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutLog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ExerciseId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ExerciseId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Workout.Model.WorkoutLog", b =>
                {
                    b.HasOne("Workout.Model.Exercise", "Exercise")
                        .WithMany("WorkoutLog")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout.Model.User", "User")
                        .WithMany("WorkoutLog")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workout.Model.Exercise", b =>
                {
                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("Workout.Model.User", b =>
                {
                    b.Navigation("WorkoutLog");
                });
#pragma warning restore 612, 618
        }
    }
}
