// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RazorPagesGreatHouse.Migrations
{
    [DbContext(typeof(Vvardenfell))]
    partial class VvardenfellModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GreatHouse.Model.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Characteristic")
                        .HasColumnType("TEXT");

                    b.Property<int>("Clan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Slaver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Characteristic = "Greedy",
                            Clan = 0,
                            Slaver = false,
                            Strength = 50000
                        },
                        new
                        {
                            Id = 2,
                            Characteristic = "Traditionalist",
                            Clan = 1,
                            Slaver = false,
                            Strength = 10000
                        });
                });

            modelBuilder.Entity("GreatHouse.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Health = 50,
                            HouseId = 1,
                            Level = 10,
                            Name = "Umbacano",
                            Race = 7
                        },
                        new
                        {
                            Id = 2,
                            Health = 25,
                            HouseId = 1,
                            Level = 5,
                            Name = "Zainsubani",
                            Race = 8
                        },
                        new
                        {
                            Id = 3,
                            Health = 200,
                            HouseId = 2,
                            Level = 30,
                            Name = "Smelrik",
                            Race = 6
                        },
                        new
                        {
                            Id = 4,
                            Health = 200,
                            HouseId = 2,
                            Level = 50,
                            Name = "Sotha",
                            Race = 8
                        },
                        new
                        {
                            Id = 5,
                            Health = 30,
                            HouseId = 2,
                            Level = 4,
                            Name = "Gamer",
                            Race = 0
                        });
                });

            modelBuilder.Entity("GreatHouse.Model.Person", b =>
                {
                    b.HasOne("GreatHouse.Model.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
